package com.hbase.bulkload.txt;

import java.util.ArrayList;

public class HColumnText {
    public static final byte[] TIME_STAMP = "time_stamp".getBytes();
    public static final byte[] S_HOUR = "s_hour".getBytes();
    public static final byte[] S_5MIN = "s_5min".getBytes();
    public static final byte[] IS_MR_INCLUDED = "is_mr_included".getBytes();
    public static final byte[] LON = "lon".getBytes();
    public static final byte[] LAT = "lat".getBytes();
    public static final byte[] INIT_LON = "init_lon".getBytes();
    public static final byte[] INIT_LAT = "init_lat".getBytes();
    public static final byte[] LAST_LON = "last_lon".getBytes();
    public static final byte[] LAST_LAT = "last_lat".getBytes();
    public static final byte[] GRID_ROW = "grid_row".getBytes();
    public static final byte[] GRID_COL = "grid_col".getBytes();
    public static final byte[] ALGORITHM_ACCURACY = "algorithm_accuracy".getBytes();
    public static final byte[] ALGORITHM_SAMPLING = "algorithm_sampling".getBytes();
    public static final byte[] CDL_PROCESS_STATUS = "cdl_process_status".getBytes();
    public static final byte[] CDL_STATUS = "cdl_status".getBytes();
    public static final byte[] CDL_STATUS_SORT = "cdl_status_sort".getBytes();
    public static final byte[] CDL_ABNORMAL_DESC = "cdl_abnormal_desc".getBytes();
    public static final byte[] INIT_ONEWAY_DELAY_DISTANCE = "init_oneway_delay_distance".getBytes();
    public static final byte[] LAST_ONEWAY_DELAY_DISTANCE = "last_oneway_delay_distance".getBytes();
    public static final byte[] INSERT_TIME = "insert_time".getBytes();
    public static final byte[] VENDOR_ID = "vendor_id".getBytes();
    public static final byte[] VERSION_ID = "version_id".getBytes();
    public static final byte[] CITY_ID = "city_id".getBytes();
    public static final byte[] CALL_TYPE = "call_type".getBytes();
    public static final byte[] CUR_PHONE_NUMBER = "cur_phone_number".getBytes();
    public static final byte[] IMSI = "imsi".getBytes();
    public static final byte[] IMSI_3G = "imsi_3g".getBytes();
    public static final byte[] CUR_NUMBER_PROVINCE = "cur_number_province".getBytes();
    public static final byte[] CUR_NUMBER_CITY = "cur_number_city".getBytes();
    public static final byte[] CUR_NUMBER_COUNTRY = "cur_number_country".getBytes();
    public static final byte[] IMEI = "imei".getBytes();
    public static final byte[] MOBILE_MANUFACTURE = "mobile_manufacture".getBytes();
    public static final byte[] MOBILE_MODEL = "mobile_model".getBytes();
    public static final byte[] SERVICE_TYPE = "service_type".getBytes();
    public static final byte[] CALL_START_TIME = "call_start_time".getBytes();
    public static final byte[] CALL_END_TIME = "call_end_time".getBytes();
    public static final byte[] CALL_LEN = "call_len".getBytes();
    public static final byte[] INIT_ENODEB_OID = "init_enodeb_oid".getBytes();
    public static final byte[] INIT_CALL_OID = "init_call_oid".getBytes();
    public static final byte[] LAST_ENODEB_OID = "last_enodeb_oid".getBytes();
    public static final byte[] LAST_CALL_OID = "last_call_oid".getBytes();
    public static final byte[] CDR_CALLID = "cdr_callid".getBytes();
    public static final byte[] CDR_MMEGROUPID = "cdr_mmegroupid".getBytes();
    public static final byte[] CDR_MMECODE = "cdr_mmecode".getBytes();
    public static final byte[] CDR_ENODEBID = "cdr_enodebid".getBytes();
    public static final byte[] CDR_STMSI = "cdr_stmsi".getBytes();
    public static final byte[] CDR_MMEUES1APID = "cdr_mmeues1apid".getBytes();
    public static final byte[] CDR_ENBUES1APID = "cdr_enbues1apid".getBytes();
    public static final byte[] CDR_STARTTIME = "cdr_starttime".getBytes();
    public static final byte[] CDR_ENDTIME = "cdr_endtime".getBytes();
    public static final byte[] CDR_TYPE = "cdr_type".getBytes();
    public static final byte[] CDR_TXBYTE = "cdr_txbyte".getBytes();
    public static final byte[] CDR_RXBYTE = "cdr_rxbyte".getBytes();
    public static final byte[] CDR_CA_ID = "cdr_ca_id".getBytes();
    public static final byte[] CDR_MIMO_ID = "cdr_mimo_id".getBytes();
    public static final byte[] AC_RRCSTARTTIME = "ac_rrcstarttime".getBytes();
    public static final byte[] AC_RRCESTABLISHMENTCAUSE = "ac_rrcestablishmentcause".getBytes();
    public static final byte[] AC_RRCFAILURECAUSE = "ac_rrcfailurecause".getBytes();
    public static final byte[] AC_TAI = "ac_tai".getBytes();
    public static final byte[] AC_CELLID = "ac_cellid".getBytes();
    public static final byte[] AC_PCI = "ac_pci".getBytes();
    public static final byte[] AC_MMEIP = "ac_mmeip".getBytes();
    public static final byte[] AC_SGWIP = "ac_sgwip".getBytes();
    public static final byte[] AC_CRNTI = "ac_crnti".getBytes();
    public static final byte[] AC_BEFOREREESTABLISHMENTPCI = "ac_beforereestablishmentpci".getBytes();
    public static final byte[] AC_CALLTIME = "ac_calltime".getBytes();
    public static final byte[] AC_MR_LTESCTADV = "ac_mr_ltesctadv".getBytes();
    public static final byte[] AC_TM = "ac_tm".getBytes();
    public static final byte[] AC_MR_LTESCCQI = "ac_mr_ltesccqi".getBytes();
    public static final byte[] AC_MR_LTESCRI = "ac_mr_ltescri".getBytes();
    public static final byte[] AC_MR_LTESCRSRP = "ac_mr_ltescrsrp".getBytes();
    public static final byte[] AC_MR_LTESCRSRQ = "ac_mr_ltescrsrq".getBytes();
    public static final byte[] AC_MR_LTESCPHR = "ac_mr_ltescphr".getBytes();
    public static final byte[] AC_MR_LTESCEARFCN = "ac_mr_ltescearfcn".getBytes();
    public static final byte[] AC_MR_LTENCRSRP1 = "ac_mr_ltencrsrp1".getBytes();
    public static final byte[] AC_MR_LTENCRSRQ1 = "ac_mr_ltencrsrq1".getBytes();
    public static final byte[] AC_MR_LTENCPCI1 = "ac_mr_ltencpci1".getBytes();
    public static final byte[] AC_MR_LTENCEARFCN1 = "ac_mr_ltencearfcn1".getBytes();
    public static final byte[] AC_MR_LTENCRSRP2 = "ac_mr_ltencrsrp2".getBytes();
    public static final byte[] AC_MR_LTENCRSRQ2 = "ac_mr_ltencrsrq2".getBytes();
    public static final byte[] AC_MR_LTENCPCI2 = "ac_mr_ltencpci2".getBytes();
    public static final byte[] AC_MR_LTENCEARFCN2 = "ac_mr_ltencearfcn2".getBytes();
    public static final byte[] AC_MR_LTENCRSRP3 = "ac_mr_ltencrsrp3".getBytes();
    public static final byte[] AC_MR_LTENCRSRQ3 = "ac_mr_ltencrsrq3".getBytes();
    public static final byte[] AC_MR_LTENCPCI3 = "ac_mr_ltencpci3".getBytes();
    public static final byte[] AC_MR_LTENCEARFCN3 = "ac_mr_ltencearfcn3".getBytes();
    public static final byte[] AC_MR_LTENCRSRP4 = "ac_mr_ltencrsrp4".getBytes();
    public static final byte[] AC_MR_LTENCRSRQ4 = "ac_mr_ltencrsrq4".getBytes();
    public static final byte[] AC_MR_LTENCPCI4 = "ac_mr_ltencpci4".getBytes();
    public static final byte[] AC_MR_LTENCEARFCN4 = "ac_mr_ltencearfcn4".getBytes();
    public static final byte[] AC_MR_LTENCRSRP5 = "ac_mr_ltencrsrp5".getBytes();
    public static final byte[] AC_MR_LTENCRSRQ5 = "ac_mr_ltencrsrq5".getBytes();
    public static final byte[] AC_MR_LTENCPCI5 = "ac_mr_ltencpci5".getBytes();
    public static final byte[] AC_MR_LTENCEARFCN5 = "ac_mr_ltencearfcn5".getBytes();
    public static final byte[] AC_MR_LTENCRSRP6 = "ac_mr_ltencrsrp6".getBytes();
    public static final byte[] AC_MR_LTENCRSRQ6 = "ac_mr_ltencrsrq6".getBytes();
    public static final byte[] AC_MR_LTENCPCI6 = "ac_mr_ltencpci6".getBytes();
    public static final byte[] AC_MR_LTENCEARFCN6 = "ac_mr_ltencearfcn6".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI1 = "ac_mr_ltescplrulqci1".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI2 = "ac_mr_ltescplrulqci2".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI3 = "ac_mr_ltescplrulqci3".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI4 = "ac_mr_ltescplrulqci4".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI5 = "ac_mr_ltescplrulqci5".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI6 = "ac_mr_ltescplrulqci6".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI7 = "ac_mr_ltescplrulqci7".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI8 = "ac_mr_ltescplrulqci8".getBytes();
    public static final byte[] AC_MR_LTESCPLRULQCI9 = "ac_mr_ltescplrulqci9".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI1 = "ac_mr_ltescplrdlqci1".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI2 = "ac_mr_ltescplrdlqci2".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI3 = "ac_mr_ltescplrdlqci3".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI4 = "ac_mr_ltescplrdlqci4".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI5 = "ac_mr_ltescplrdlqci5".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI6 = "ac_mr_ltescplrdlqci6".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI7 = "ac_mr_ltescplrdlqci7".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI8 = "ac_mr_ltescplrdlqci8".getBytes();
    public static final byte[] AC_MR_LTESCPLRDLQCI9 = "ac_mr_ltescplrdlqci9".getBytes();
    public static final byte[] AC_MR_LTESCRIP = "ac_mr_ltescrip".getBytes();
    public static final byte[] AC_MR_LTESCSINRUL = "ac_mr_ltescsinrul".getBytes();
    public static final byte[] AC_RRCENDTIME = "ac_rrcendtime".getBytes();
    public static final byte[] AC_LONGITUDE = "ac_longitude".getBytes();
    public static final byte[] AC_LATITUDE = "ac_latitude".getBytes();
    public static final byte[] AC_CELLRBPAYLOAD = "ac_cellrbpayload".getBytes();
    public static final byte[] AC_CELLPDCCHPAYLOAD = "ac_cellpdcchpayload".getBytes();
    public static final byte[] AC_CELLPRACHPAYLOAD = "ac_cellprachpayload".getBytes();
    public static final byte[] AC_CELLACTUSERNUM = "ac_cellactusernum".getBytes();
    public static final byte[] AC_CELLULRSSI = "ac_cellulrssi".getBytes();
    public static final byte[] ERAB_UE_ULAMBR = "erab_ue_ulambr".getBytes();
    public static final byte[] ERAB_UE_DLAMBR = "erab_ue_dlambr".getBytes();
    public static final byte[] ERAB_RBID_1 = "erab_rbid_1".getBytes();
    public static final byte[] ERAB_ERABID_1 = "erab_erabid_1".getBytes();
    public static final byte[] ERAB_QCI_1 = "erab_qci_1".getBytes();
    public static final byte[] ERAB_CREATETIME_1 = "erab_createtime_1".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_1 = "erab_deactivatetime_1".getBytes();
    public static final byte[] ERAB_RLSRESULT_1 = "erab_rlsresult_1".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_1 = "erab_setupfailurecause_1".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_1 = "erab_rlsfailurecause_1".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_1 = "erab_ul_pktgwcnt_1".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_1 = "erab_dl_pktgwcnt_1".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_1 = "erab_ul_bytegwcnt_1".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_1 = "erab_dl_bytegwcnt_1".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_1 = "erab_ul_pktuecnt_1".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_1 = "erab_dl_pktuecnt_1".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE1 = "erab_ul_packet_droprate1".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE1 = "erab_dl_packet_lossrate1".getBytes();
    public static final byte[] ERAB_DLMBR_1 = "erab_dlmbr_1".getBytes();
    public static final byte[] ERAB_ULMBR_1 = "erab_ulmbr_1".getBytes();
    public static final byte[] ERAB_DLGBR_1 = "erab_dlgbr_1".getBytes();
    public static final byte[] ERAB_ULGBR_1 = "erab_ulgbr_1".getBytes();
    public static final byte[] ERAB_RBID_2 = "erab_rbid_2".getBytes();
    public static final byte[] ERAB_ERABID_2 = "erab_erabid_2".getBytes();
    public static final byte[] ERAB_QCI_2 = "erab_qci_2".getBytes();
    public static final byte[] ERAB_CREATETIME_2 = "erab_createtime_2".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_2 = "erab_deactivatetime_2".getBytes();
    public static final byte[] ERAB_RLSRESULT_2 = "erab_rlsresult_2".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_2 = "erab_setupfailurecause_2".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_2 = "erab_rlsfailurecause_2".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_2 = "erab_ul_pktgwcnt_2".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_2 = "erab_dl_pktgwcnt_2".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_2 = "erab_ul_bytegwcnt_2".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_2 = "erab_dl_bytegwcnt_2".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_2 = "erab_ul_pktuecnt_2".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_2 = "erab_dl_pktuecnt_2".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE2 = "erab_ul_packet_droprate2".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE2 = "erab_dl_packet_lossrate2".getBytes();
    public static final byte[] ERAB_DLMBR_2 = "erab_dlmbr_2".getBytes();
    public static final byte[] ERAB_ULMBR_2 = "erab_ulmbr_2".getBytes();
    public static final byte[] ERAB_DLGBR_2 = "erab_dlgbr_2".getBytes();
    public static final byte[] ERAB_ULGBR_2 = "erab_ulgbr_2".getBytes();
    public static final byte[] ERAB_RBID_3 = "erab_rbid_3".getBytes();
    public static final byte[] ERAB_ERABID_3 = "erab_erabid_3".getBytes();
    public static final byte[] ERAB_QCI_3 = "erab_qci_3".getBytes();
    public static final byte[] ERAB_CREATETIME_3 = "erab_createtime_3".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_3 = "erab_deactivatetime_3".getBytes();
    public static final byte[] ERAB_RLSRESULT_3 = "erab_rlsresult_3".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_3 = "erab_setupfailurecause_3".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_3 = "erab_rlsfailurecause_3".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_3 = "erab_ul_pktgwcnt_3".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_3 = "erab_dl_pktgwcnt_3".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_3 = "erab_ul_bytegwcnt_3".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_3 = "erab_dl_bytegwcnt_3".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_3 = "erab_ul_pktuecnt_3".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_3 = "erab_dl_pktuecnt_3".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE3 = "erab_ul_packet_droprate3".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE3 = "erab_dl_packet_lossrate3".getBytes();
    public static final byte[] ERAB_DLMBR_3 = "erab_dlmbr_3".getBytes();
    public static final byte[] ERAB_ULMBR_3 = "erab_ulmbr_3".getBytes();
    public static final byte[] ERAB_DLGBR_3 = "erab_dlgbr_3".getBytes();
    public static final byte[] ERAB_ULGBR_3 = "erab_ulgbr_3".getBytes();
    public static final byte[] ERAB_RBID_4 = "erab_rbid_4".getBytes();
    public static final byte[] ERAB_ERABID_4 = "erab_erabid_4".getBytes();
    public static final byte[] ERAB_QCI_4 = "erab_qci_4".getBytes();
    public static final byte[] ERAB_CREATETIME_4 = "erab_createtime_4".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_4 = "erab_deactivatetime_4".getBytes();
    public static final byte[] ERAB_RLSRESULT_4 = "erab_rlsresult_4".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_4 = "erab_setupfailurecause_4".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_4 = "erab_rlsfailurecause_4".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_4 = "erab_ul_pktgwcnt_4".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_4 = "erab_dl_pktgwcnt_4".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_4 = "erab_ul_bytegwcnt_4".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_4 = "erab_dl_bytegwcnt_4".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_4 = "erab_ul_pktuecnt_4".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_4 = "erab_dl_pktuecnt_4".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE4 = "erab_ul_packet_droprate4".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE4 = "erab_dl_packet_lossrate4".getBytes();
    public static final byte[] ERAB_DLMBR_4 = "erab_dlmbr_4".getBytes();
    public static final byte[] ERAB_ULMBR_4 = "erab_ulmbr_4".getBytes();
    public static final byte[] ERAB_DLGBR_4 = "erab_dlgbr_4".getBytes();
    public static final byte[] ERAB_ULGBR_4 = "erab_ulgbr_4".getBytes();
    public static final byte[] ERAB_RBID_5 = "erab_rbid_5".getBytes();
    public static final byte[] ERAB_ERABID_5 = "erab_erabid_5".getBytes();
    public static final byte[] ERAB_QCI_5 = "erab_qci_5".getBytes();
    public static final byte[] ERAB_CREATETIME_5 = "erab_createtime_5".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_5 = "erab_deactivatetime_5".getBytes();
    public static final byte[] ERAB_RLSRESULT_5 = "erab_rlsresult_5".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_5 = "erab_setupfailurecause_5".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_5 = "erab_rlsfailurecause_5".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_5 = "erab_ul_pktgwcnt_5".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_5 = "erab_dl_pktgwcnt_5".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_5 = "erab_ul_bytegwcnt_5".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_5 = "erab_dl_bytegwcnt_5".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_5 = "erab_ul_pktuecnt_5".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_5 = "erab_dl_pktuecnt_5".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE5 = "erab_ul_packet_droprate5".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE5 = "erab_dl_packet_lossrate5".getBytes();
    public static final byte[] ERAB_DLMBR_5 = "erab_dlmbr_5".getBytes();
    public static final byte[] ERAB_ULMBR_5 = "erab_ulmbr_5".getBytes();
    public static final byte[] ERAB_DLGBR_5 = "erab_dlgbr_5".getBytes();
    public static final byte[] ERAB_ULGBR_5 = "erab_ulgbr_5".getBytes();
    public static final byte[] ERAB_RBID_6 = "erab_rbid_6".getBytes();
    public static final byte[] ERAB_ERABID_6 = "erab_erabid_6".getBytes();
    public static final byte[] ERAB_QCI_6 = "erab_qci_6".getBytes();
    public static final byte[] ERAB_CREATETIME_6 = "erab_createtime_6".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_6 = "erab_deactivatetime_6".getBytes();
    public static final byte[] ERAB_RLSRESULT_6 = "erab_rlsresult_6".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_6 = "erab_setupfailurecause_6".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_6 = "erab_rlsfailurecause_6".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_6 = "erab_ul_pktgwcnt_6".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_6 = "erab_dl_pktgwcnt_6".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_6 = "erab_ul_bytegwcnt_6".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_6 = "erab_dl_bytegwcnt_6".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_6 = "erab_ul_pktuecnt_6".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_6 = "erab_dl_pktuecnt_6".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE6 = "erab_ul_packet_droprate6".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE6 = "erab_dl_packet_lossrate6".getBytes();
    public static final byte[] ERAB_DLMBR_6 = "erab_dlmbr_6".getBytes();
    public static final byte[] ERAB_ULMBR_6 = "erab_ulmbr_6".getBytes();
    public static final byte[] ERAB_DLGBR_6 = "erab_dlgbr_6".getBytes();
    public static final byte[] ERAB_ULGBR_6 = "erab_ulgbr_6".getBytes();
    public static final byte[] ERAB_RBID_7 = "erab_rbid_7".getBytes();
    public static final byte[] ERAB_ERABID_7 = "erab_erabid_7".getBytes();
    public static final byte[] ERAB_QCI_7 = "erab_qci_7".getBytes();
    public static final byte[] ERAB_CREATETIME_7 = "erab_createtime_7".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_7 = "erab_deactivatetime_7".getBytes();
    public static final byte[] ERAB_RLSRESULT_7 = "erab_rlsresult_7".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_7 = "erab_setupfailurecause_7".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_7 = "erab_rlsfailurecause_7".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_7 = "erab_ul_pktgwcnt_7".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_7 = "erab_dl_pktgwcnt_7".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_7 = "erab_ul_bytegwcnt_7".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_7 = "erab_dl_bytegwcnt_7".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_7 = "erab_ul_pktuecnt_7".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_7 = "erab_dl_pktuecnt_7".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE7 = "erab_ul_packet_droprate7".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE7 = "erab_dl_packet_lossrate7".getBytes();
    public static final byte[] ERAB_DLMBR_7 = "erab_dlmbr_7".getBytes();
    public static final byte[] ERAB_ULMBR_7 = "erab_ulmbr_7".getBytes();
    public static final byte[] ERAB_DLGBR_7 = "erab_dlgbr_7".getBytes();
    public static final byte[] ERAB_ULGBR_7 = "erab_ulgbr_7".getBytes();
    public static final byte[] ERAB_RBID_8 = "erab_rbid_8".getBytes();
    public static final byte[] ERAB_ERABID_8 = "erab_erabid_8".getBytes();
    public static final byte[] ERAB_QCI_8 = "erab_qci_8".getBytes();
    public static final byte[] ERAB_CREATETIME_8 = "erab_createtime_8".getBytes();
    public static final byte[] ERAB_DEACTIVATETIME_8 = "erab_deactivatetime_8".getBytes();
    public static final byte[] ERAB_RLSRESULT_8 = "erab_rlsresult_8".getBytes();
    public static final byte[] ERAB_SETUPFAILURECAUSE_8 = "erab_setupfailurecause_8".getBytes();
    public static final byte[] ERAB_RLSFAILURECAUSE_8 = "erab_rlsfailurecause_8".getBytes();
    public static final byte[] ERAB_UL_PKTGWCNT_8 = "erab_ul_pktgwcnt_8".getBytes();
    public static final byte[] ERAB_DL_PKTGWCNT_8 = "erab_dl_pktgwcnt_8".getBytes();
    public static final byte[] ERAB_UL_BYTEGWCNT_8 = "erab_ul_bytegwcnt_8".getBytes();
    public static final byte[] ERAB_DL_BYTEGWCNT_8 = "erab_dl_bytegwcnt_8".getBytes();
    public static final byte[] ERAB_UL_PKTUECNT_8 = "erab_ul_pktuecnt_8".getBytes();
    public static final byte[] ERAB_DL_PKTUECNT_8 = "erab_dl_pktuecnt_8".getBytes();
    public static final byte[] ERAB_UL_PACKET_DROPRATE8 = "erab_ul_packet_droprate8".getBytes();
    public static final byte[] ERAB_DL_PACKET_LOSSRATE8 = "erab_dl_packet_lossrate8".getBytes();
    public static final byte[] ERAB_DLMBR_8 = "erab_dlmbr_8".getBytes();
    public static final byte[] ERAB_ULMBR_8 = "erab_ulmbr_8".getBytes();
    public static final byte[] ERAB_DLGBR_8 = "erab_dlgbr_8".getBytes();
    public static final byte[] ERAB_ULGBR_8 = "erab_ulgbr_8".getBytes();
    public static final byte[] ERAB_DATA_TRANS_UPTIME = "erab_data_trans_uptime".getBytes();
    public static final byte[] ERAB_DATA_TRANS_DOWNTIME = "erab_data_trans_downtime".getBytes();
    public static final byte[] ERAB_TOTAL_UPDATA = "erab_total_updata".getBytes();
    public static final byte[] ERAB_TOTAL_DOWNDATA = "erab_total_downdata".getBytes();
    public static final byte[] ERAB_DL_NODATAGWCNTQCI1 = "erab_dl_nodatagwcntqci1".getBytes();
    public static final byte[] ERAB_UL_NODATAGWCNTQCI1 = "erab_ul_nodatagwcntqci1".getBytes();
    public static final byte[] ERAB_TYPE = "erab_type".getBytes();
    public static final byte[] HO_FIRST_STARTTIME = "ho_first_starttime".getBytes();
    public static final byte[] HO_FIRST_STARTTIMEMILLISEC = "ho_first_starttimemillisec".getBytes();
    public static final byte[] HO_FIRST_EVENTTYPE = "ho_first_eventtype".getBytes();
    public static final byte[] HO_FIRST_EVENTTIME = "ho_first_eventtime".getBytes();
    public static final byte[] HO_FIRST_TYPE = "ho_first_type".getBytes();
    public static final byte[] HO_FIRST_INTERFACETYPE = "ho_first_interfacetype".getBytes();
    public static final byte[] HO_FIRST_SRCMCC = "ho_first_srcmcc".getBytes();
    public static final byte[] HO_FIRST_SRCMNC = "ho_first_srcmnc".getBytes();
    public static final byte[] HO_FIRST_SRCTAC = "ho_first_srctac".getBytes();
    public static final byte[] HO_FIRST_SRCCELLID = "ho_first_srccellid".getBytes();
    public static final byte[] HO_FIRST_SRCPCI = "ho_first_srcpci".getBytes();
    public static final byte[] HO_FIRST_TGTMCC = "ho_first_tgtmcc".getBytes();
    public static final byte[] HO_FIRST_TGTMNC = "ho_first_tgtmnc".getBytes();
    public static final byte[] HO_FIRST_TGTTAC = "ho_first_tgttac".getBytes();
    public static final byte[] HO_FIRST_TGTCELLID = "ho_first_tgtcellid".getBytes();
    public static final byte[] HO_FIRST_TGTPCI = "ho_first_tgtpci".getBytes();
    public static final byte[] HO_FIRST_RESULT = "ho_first_result".getBytes();
    public static final byte[] HO_FIRST_FAILURECAUSE = "ho_first_failurecause".getBytes();
    public static final byte[] HO_FIRST_ENDTIME = "ho_first_endtime".getBytes();
    public static final byte[] HO_FIRST_ENDTIMEMILLISEC = "ho_first_endtimemillisec".getBytes();
    public static final byte[] HO_FIRST_SRCULFREQ = "ho_first_srculfreq".getBytes();
    public static final byte[] HO_FIRST_SRCDLFREQ = "ho_first_srcdlfreq".getBytes();
    public static final byte[] HO_FIRST_TGTULFREQ = "ho_first_tgtulfreq".getBytes();
    public static final byte[] HO_FIRST_TGTDLFREQ = "ho_first_tgtdlfreq".getBytes();
    public static final byte[] HO_FIRST_SRCDLBANDWIDTH = "ho_first_srcdlbandwidth".getBytes();
    public static final byte[] HO_FIRST_TGTDLBANDWIDTH = "ho_first_tgtdlbandwidth".getBytes();
    public static final byte[] HO_FIRST_SRCRSRP = "ho_first_srcrsrp".getBytes();
    public static final byte[] HO_FIRST_SRCRSRQ = "ho_first_srcrsrq".getBytes();
    public static final byte[] HO_FIRST_TGTRSRP = "ho_first_tgtrsrp".getBytes();
    public static final byte[] HO_FIRST_TGTRSRQ = "ho_first_tgtrsrq".getBytes();
    public static final byte[] HO_FIRST_NCNUM = "ho_first_ncnum".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCECGI1 = "ho_first_mr_ltencecgi1".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCPCI1 = "ho_first_mr_ltencpci1".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRP1 = "ho_first_mr_ltencrsrp1".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRQ1 = "ho_first_mr_ltencrsrq1".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCECGI2 = "ho_first_mr_ltencecgi2".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCPCI2 = "ho_first_mr_ltencpci2".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRP2 = "ho_first_mr_ltencrsrp2".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRQ2 = "ho_first_mr_ltencrsrq2".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCECGI3 = "ho_first_mr_ltencecgi3".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCPCI3 = "ho_first_mr_ltencpci3".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRP3 = "ho_first_mr_ltencrsrp3".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRQ3 = "ho_first_mr_ltencrsrq3".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCECGI4 = "ho_first_mr_ltencecgi4".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCPCI4 = "ho_first_mr_ltencpci4".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRP4 = "ho_first_mr_ltencrsrp4".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRQ4 = "ho_first_mr_ltencrsrq4".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCECGI5 = "ho_first_mr_ltencecgi5".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCPCI5 = "ho_first_mr_ltencpci5".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRP5 = "ho_first_mr_ltencrsrp5".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRQ5 = "ho_first_mr_ltencrsrq5".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCECGI6 = "ho_first_mr_ltencecgi6".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCPCI6 = "ho_first_mr_ltencpci6".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRP6 = "ho_first_mr_ltencrsrp6".getBytes();
    public static final byte[] HO_FIRST_MR_LTENCRSRQ6 = "ho_first_mr_ltencrsrq6".getBytes();
    public static final byte[] HO_FIRST_MR_LTESCRIP = "ho_first_mr_ltescrip".getBytes();
    public static final byte[] HO_FIRST_MR_LTESCSINRUL = "ho_first_mr_ltescsinrul".getBytes();
    public static final byte[] HO_LAST_STARTTIME = "ho_last_starttime".getBytes();
    public static final byte[] HO_LAST_STARTTIMEMILLISEC = "ho_last_starttimemillisec".getBytes();
    public static final byte[] HO_LAST_EVENTTYPE = "ho_last_eventtype".getBytes();
    public static final byte[] HO_LAST_EVENTTIME = "ho_last_eventtime".getBytes();
    public static final byte[] HO_LAST_TYPE = "ho_last_type".getBytes();
    public static final byte[] HO_LAST_INTERFACETYPE = "ho_last_interfacetype".getBytes();
    public static final byte[] HO_LAST_SRCMCC = "ho_last_srcmcc".getBytes();
    public static final byte[] HO_LAST_SRCMNC = "ho_last_srcmnc".getBytes();
    public static final byte[] HO_LAST_SRCTAC = "ho_last_srctac".getBytes();
    public static final byte[] HO_LAST_SRCCELLID = "ho_last_srccellid".getBytes();
    public static final byte[] HO_LAST_SRCPCI = "ho_last_srcpci".getBytes();
    public static final byte[] HO_LAST_TGTMCC = "ho_last_tgtmcc".getBytes();
    public static final byte[] HO_LAST_TGTMNC = "ho_last_tgtmnc".getBytes();
    public static final byte[] HO_LAST_TGTTAC = "ho_last_tgttac".getBytes();
    public static final byte[] HO_LAST_TGTCELLID = "ho_last_tgtcellid".getBytes();
    public static final byte[] HO_LAST_TGTPCI = "ho_last_tgtpci".getBytes();
    public static final byte[] HO_LAST_RESULT = "ho_last_result".getBytes();
    public static final byte[] HO_LAST_FAILURECAUSE = "ho_last_failurecause".getBytes();
    public static final byte[] HO_LAST_ENDTIME = "ho_last_endtime".getBytes();
    public static final byte[] HO_LAST_ENDTIMEMILLISEC = "ho_last_endtimemillisec".getBytes();
    public static final byte[] HO_LAST_SRCULFREQ = "ho_last_srculfreq".getBytes();
    public static final byte[] HO_LAST_SRCDLFREQ = "ho_last_srcdlfreq".getBytes();
    public static final byte[] HO_LAST_TGTULFREQ = "ho_last_tgtulfreq".getBytes();
    public static final byte[] HO_LAST_TGTDLFREQ = "ho_last_tgtdlfreq".getBytes();
    public static final byte[] HO_LAST_SRCDLBANDWIDTH = "ho_last_srcdlbandwidth".getBytes();
    public static final byte[] HO_LAST_TGTDLBANDWIDTH = "ho_last_tgtdlbandwidth".getBytes();
    public static final byte[] HO_LAST_SRCRSRP = "ho_last_srcrsrp".getBytes();
    public static final byte[] HO_LAST_SRCRSRQ = "ho_last_srcrsrq".getBytes();
    public static final byte[] HO_LAST_TGTRSRP = "ho_last_tgtrsrp".getBytes();
    public static final byte[] HO_LAST_TGTRSRQ = "ho_last_tgtrsrq".getBytes();
    public static final byte[] HO_LAST_NCNUM = "ho_last_ncnum".getBytes();
    public static final byte[] HO_LAST_MR_LTENCECGI1 = "ho_last_mr_ltencecgi1".getBytes();
    public static final byte[] HO_LAST_MR_LTENCPCI1 = "ho_last_mr_ltencpci1".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRP1 = "ho_last_mr_ltencrsrp1".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRQ1 = "ho_last_mr_ltencrsrq1".getBytes();
    public static final byte[] HO_LAST_MR_LTENCECGI2 = "ho_last_mr_ltencecgi2".getBytes();
    public static final byte[] HO_LAST_MR_LTENCPCI2 = "ho_last_mr_ltencpci2".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRP2 = "ho_last_mr_ltencrsrp2".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRQ2 = "ho_last_mr_ltencrsrq2".getBytes();
    public static final byte[] HO_LAST_MR_LTENCECGI3 = "ho_last_mr_ltencecgi3".getBytes();
    public static final byte[] HO_LAST_MR_LTENCPCI3 = "ho_last_mr_ltencpci3".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRP3 = "ho_last_mr_ltencrsrp3".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRQ3 = "ho_last_mr_ltencrsrq3".getBytes();
    public static final byte[] HO_LAST_MR_LTENCECGI4 = "ho_last_mr_ltencecgi4".getBytes();
    public static final byte[] HO_LAST_MR_LTENCPCI4 = "ho_last_mr_ltencpci4".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRP4 = "ho_last_mr_ltencrsrp4".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRQ4 = "ho_last_mr_ltencrsrq4".getBytes();
    public static final byte[] HO_LAST_MR_LTENCECGI5 = "ho_last_mr_ltencecgi5".getBytes();
    public static final byte[] HO_LAST_MR_LTENCPCI5 = "ho_last_mr_ltencpci5".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRP5 = "ho_last_mr_ltencrsrp5".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRQ5 = "ho_last_mr_ltencrsrq5".getBytes();
    public static final byte[] HO_LAST_MR_LTENCECGI6 = "ho_last_mr_ltencecgi6".getBytes();
    public static final byte[] HO_LAST_MR_LTENCPCI6 = "ho_last_mr_ltencpci6".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRP6 = "ho_last_mr_ltencrsrp6".getBytes();
    public static final byte[] HO_LAST_MR_LTENCRSRQ6 = "ho_last_mr_ltencrsrq6".getBytes();
    public static final byte[] HO_LAST_MR_LTESCRIP = "ho_last_mr_ltescrip".getBytes();
    public static final byte[] HO_LAST_MR_LTESCSINRUL = "ho_last_mr_ltescsinrul".getBytes();
    public static final byte[] HO_LAST_CURRENTSGWID = "ho_last_currentsgwid".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_1 = "ho_historycellecgi_1".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_1 = "ho_historycellsize_1".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_1 = "ho_historystaytime_1".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_2 = "ho_historycellecgi_2".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_2 = "ho_historycellsize_2".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_2 = "ho_historystaytime_2".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_3 = "ho_historycellecgi_3".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_3 = "ho_historycellsize_3".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_3 = "ho_historystaytime_3".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_4 = "ho_historycellecgi_4".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_4 = "ho_historycellsize_4".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_4 = "ho_historystaytime_4".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_5 = "ho_historycellecgi_5".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_5 = "ho_historycellsize_5".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_5 = "ho_historystaytime_5".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_6 = "ho_historycellecgi_6".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_6 = "ho_historycellsize_6".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_6 = "ho_historystaytime_6".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_7 = "ho_historycellecgi_7".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_7 = "ho_historycellsize_7".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_7 = "ho_historystaytime_7".getBytes();
    public static final byte[] HO_HISTORYCELLECGI_8 = "ho_historycellecgi_8".getBytes();
    public static final byte[] HO_HISTORYCELLSIZE_8 = "ho_historycellsize_8".getBytes();
    public static final byte[] HO_HISTORYSTAYTIME_8 = "ho_historystaytime_8".getBytes();
    public static final byte[] RLS_CALLRELEASETIME = "rls_callreleasetime".getBytes();
    public static final byte[] RLS_TAI = "rls_tai".getBytes();
    public static final byte[] RLS_CELLID = "rls_cellid".getBytes();
    public static final byte[] RLS_PCI = "rls_pci".getBytes();
    public static final byte[] RLS_MMEIP = "rls_mmeip".getBytes();
    public static final byte[] RLS_SGWIP = "rls_sgwip".getBytes();
    public static final byte[] RLS_MR_LTESCCQI = "rls_mr_ltesccqi".getBytes();
    public static final byte[] RLS_TM = "rls_tm".getBytes();
    public static final byte[] RLS_MR_LTESCRI = "rls_mr_ltescri".getBytes();
    public static final byte[] RLS_RRCRESULT = "rls_rrcresult".getBytes();
    public static final byte[] RLS_CALLRELEASECAUSE = "rls_callreleasecause".getBytes();
    public static final byte[] RLS_MR_LTESCRIP = "rls_mr_ltescrip".getBytes();
    public static final byte[] RLS_MR_LTESCSINRUL = "rls_mr_ltescsinrul".getBytes();
    public static final byte[] RLS_MR_LTESCTADV = "rls_mr_ltesctadv".getBytes();
    public static final byte[] RLS_MR_LTESCRSRP = "rls_mr_ltescrsrp".getBytes();
    public static final byte[] RLS_MR_LTESCRSRQ = "rls_mr_ltescrsrq".getBytes();
    public static final byte[] RLS_MR_LTESCPHR = "rls_mr_ltescphr".getBytes();
    public static final byte[] RLS_MR_LTESCEARFCN = "rls_mr_ltescearfcn".getBytes();
    public static final byte[] RLS_MR_LTENCRSRP1 = "rls_mr_ltencrsrp1".getBytes();
    public static final byte[] RLS_MR_LTENCRSRQ1 = "rls_mr_ltencrsrq1".getBytes();
    public static final byte[] RLS_MR_LTENCPCI1 = "rls_mr_ltencpci1".getBytes();
    public static final byte[] RLS_MR_LTENCEARFCN1 = "rls_mr_ltencearfcn1".getBytes();
    public static final byte[] RLS_MR_LTENCRSRP2 = "rls_mr_ltencrsrp2".getBytes();
    public static final byte[] RLS_MR_LTENCRSRQ2 = "rls_mr_ltencrsrq2".getBytes();
    public static final byte[] RLS_MR_LTENCPCI2 = "rls_mr_ltencpci2".getBytes();
    public static final byte[] RLS_MR_LTENCEARFCN2 = "rls_mr_ltencearfcn2".getBytes();
    public static final byte[] RLS_MR_LTENCRSRP3 = "rls_mr_ltencrsrp3".getBytes();
    public static final byte[] RLS_MR_LTENCRSRQ3 = "rls_mr_ltencrsrq3".getBytes();
    public static final byte[] RLS_MR_LTENCPCI3 = "rls_mr_ltencpci3".getBytes();
    public static final byte[] RLS_MR_LTENCEARFCN3 = "rls_mr_ltencearfcn3".getBytes();
    public static final byte[] RLS_MR_LTENCRSRP4 = "rls_mr_ltencrsrp4".getBytes();
    public static final byte[] RLS_MR_LTENCRSRQ4 = "rls_mr_ltencrsrq4".getBytes();
    public static final byte[] RLS_MR_LTENCPCI4 = "rls_mr_ltencpci4".getBytes();
    public static final byte[] RLS_MR_LTENCEARFCN4 = "rls_mr_ltencearfcn4".getBytes();
    public static final byte[] RLS_MR_LTENCRSRP5 = "rls_mr_ltencrsrp5".getBytes();
    public static final byte[] RLS_MR_LTENCRSRQ5 = "rls_mr_ltencrsrq5".getBytes();
    public static final byte[] RLS_MR_LTENCPCI5 = "rls_mr_ltencpci5".getBytes();
    public static final byte[] RLS_MR_LTENCEARFCN5 = "rls_mr_ltencearfcn5".getBytes();
    public static final byte[] RLS_MR_LTENCRSRP6 = "rls_mr_ltencrsrp6".getBytes();
    public static final byte[] RLS_MR_LTENCRSRQ6 = "rls_mr_ltencrsrq6".getBytes();
    public static final byte[] RLS_MR_LTENCPCI6 = "rls_mr_ltencpci6".getBytes();
    public static final byte[] RLS_MR_LTENCEARFCN6 = "rls_mr_ltencearfcn6".getBytes();
    public static final byte[] RLS_REDIRECTION_TIME = "rls_redirection_time".getBytes();
    public static final byte[] RLS_REDIRECTION_SYSTEM = "rls_redirection_system".getBytes();
    public static final byte[] RLS_REDIRECTION_EARFCN = "rls_redirection_earfcn".getBytes();
    public static final byte[] RLS_LONGITUDE = "rls_longitude".getBytes();
    public static final byte[] RLS_LATITUDE = "rls_latitude".getBytes();
    public static final byte[] RLS_CELLRBPAYLOAD = "rls_cellrbpayload".getBytes();
    public static final byte[] RLS_CELLPDCCHPAYLOAD = "rls_cellpdcchpayload".getBytes();
    public static final byte[] RLS_CELLPRACHPAYLOAD = "rls_cellprachpayload".getBytes();
    public static final byte[] RLS_CELLACTUSERNUM = "rls_cellactusernum".getBytes();
    public static final byte[] RLS_RESYNCOUNT = "rls_resyncount".getBytes();
    public static final byte[] RLS_CALLSTATRELEASE = "rls_callstatrelease".getBytes();
    public static final byte[] UECAP_UECATEGORY = "uecap_uecategory".getBytes();
    public static final byte[] UECAP_RATTYPE = "uecap_rattype".getBytes();
    public static final byte[] UECAP_BANDEUTRA = "uecap_bandeutra".getBytes();
    public static final byte[] UECAP_HALFDUPLEX = "uecap_halfduplex".getBytes();
    public static final byte[] UECAP_ACCESSSTRATUMRELEASE = "uecap_accessstratumrelease".getBytes();
    public static final byte[] UECAP_FGI = "uecap_fgi".getBytes();
    public static final byte[] CDMA_TYPE = "cdma_type".getBytes();
    public static final byte[] CDMA_NCARFCN = "cdma_ncarfcn".getBytes();
    public static final byte[] CDMA_PN = "cdma_pn".getBytes();
    public static final byte[] CDMA_CI = "cdma_ci".getBytes();
    public static final byte[] CDMA_PILOTSTRENGTH = "cdma_pilotstrength".getBytes();
    public static final byte[] RLF_CONNECTIONFAILURETYPE = "rlf_connectionfailuretype".getBytes();
    public static final byte[] RLF_CELLECGI = "rlf_cellecgi".getBytes();
    public static final byte[] RLF_CELLPCI = "rlf_cellpci".getBytes();
    public static final byte[] RLF_CELLEARFCN = "rlf_cellearfcn".getBytes();
    public static final byte[] RLF_DLRSRP = "rlf_dlrsrp".getBytes();
    public static final byte[] RLF_DLRSRQ = "rlf_dlrsrq".getBytes();
    
    public static ArrayList<byte[]> cloumnList = new ArrayList<byte[]>();
    
    static {
        cloumnList.add(TIME_STAMP);
        cloumnList.add(S_HOUR);
        cloumnList.add(S_5MIN);
        cloumnList.add(IS_MR_INCLUDED);
        cloumnList.add(LON);
        cloumnList.add(LAT);
        cloumnList.add(INIT_LON);
        cloumnList.add(INIT_LAT);
        cloumnList.add(LAST_LON);
        cloumnList.add(LAST_LAT);
        cloumnList.add(GRID_ROW);
        cloumnList.add(GRID_COL);
        cloumnList.add(ALGORITHM_ACCURACY);
        cloumnList.add(ALGORITHM_SAMPLING);
        cloumnList.add(CDL_PROCESS_STATUS);
        cloumnList.add(CDL_STATUS);
        cloumnList.add(CDL_STATUS_SORT);
        cloumnList.add(CDL_ABNORMAL_DESC);
        cloumnList.add(INIT_ONEWAY_DELAY_DISTANCE);
        cloumnList.add(LAST_ONEWAY_DELAY_DISTANCE);
        cloumnList.add(INSERT_TIME);
        cloumnList.add(VENDOR_ID);
        cloumnList.add(VERSION_ID);
        cloumnList.add(CITY_ID);
        cloumnList.add(CALL_TYPE);
        cloumnList.add(CUR_PHONE_NUMBER);
        cloumnList.add(IMSI);
        cloumnList.add(IMSI_3G);
        cloumnList.add(CUR_NUMBER_PROVINCE);
        cloumnList.add(CUR_NUMBER_CITY);
        cloumnList.add(CUR_NUMBER_COUNTRY);
        cloumnList.add(IMEI);
        cloumnList.add(MOBILE_MANUFACTURE);
        cloumnList.add(MOBILE_MODEL);
        cloumnList.add(SERVICE_TYPE);
        cloumnList.add(CALL_START_TIME);
        cloumnList.add(CALL_END_TIME);
        cloumnList.add(CALL_LEN);
        cloumnList.add(INIT_ENODEB_OID);
        cloumnList.add(INIT_CALL_OID);
        cloumnList.add(LAST_ENODEB_OID);
        cloumnList.add(LAST_CALL_OID);
        cloumnList.add(CDR_CALLID);
        cloumnList.add(CDR_MMEGROUPID);
        cloumnList.add(CDR_MMECODE);
        cloumnList.add(CDR_ENODEBID);
        cloumnList.add(CDR_STMSI);
        cloumnList.add(CDR_MMEUES1APID);
        cloumnList.add(CDR_ENBUES1APID);
        cloumnList.add(CDR_STARTTIME);
        cloumnList.add(CDR_ENDTIME);
        cloumnList.add(CDR_TYPE);
        cloumnList.add(CDR_TXBYTE);
        cloumnList.add(CDR_RXBYTE);
        cloumnList.add(CDR_CA_ID);
        cloumnList.add(CDR_MIMO_ID);
        cloumnList.add(AC_RRCSTARTTIME);
        cloumnList.add(AC_RRCESTABLISHMENTCAUSE);
        cloumnList.add(AC_RRCFAILURECAUSE);
        cloumnList.add(AC_TAI);
        cloumnList.add(AC_CELLID);
        cloumnList.add(AC_PCI);
        cloumnList.add(AC_MMEIP);
        cloumnList.add(AC_SGWIP);
        cloumnList.add(AC_CRNTI);
        cloumnList.add(AC_BEFOREREESTABLISHMENTPCI);
        cloumnList.add(AC_CALLTIME);
        cloumnList.add(AC_MR_LTESCTADV);
        cloumnList.add(AC_TM);
        cloumnList.add(AC_MR_LTESCCQI);
        cloumnList.add(AC_MR_LTESCRI);
        cloumnList.add(AC_MR_LTESCRSRP);
        cloumnList.add(AC_MR_LTESCRSRQ);
        cloumnList.add(AC_MR_LTESCPHR);
        cloumnList.add(AC_MR_LTESCEARFCN);
        cloumnList.add(AC_MR_LTENCRSRP1);
        cloumnList.add(AC_MR_LTENCRSRQ1);
        cloumnList.add(AC_MR_LTENCPCI1);
        cloumnList.add(AC_MR_LTENCEARFCN1);
        cloumnList.add(AC_MR_LTENCRSRP2);
        cloumnList.add(AC_MR_LTENCRSRQ2);
        cloumnList.add(AC_MR_LTENCPCI2);
        cloumnList.add(AC_MR_LTENCEARFCN2);
        cloumnList.add(AC_MR_LTENCRSRP3);
        cloumnList.add(AC_MR_LTENCRSRQ3);
        cloumnList.add(AC_MR_LTENCPCI3);
        cloumnList.add(AC_MR_LTENCEARFCN3);
        cloumnList.add(AC_MR_LTENCRSRP4);
        cloumnList.add(AC_MR_LTENCRSRQ4);
        cloumnList.add(AC_MR_LTENCPCI4);
        cloumnList.add(AC_MR_LTENCEARFCN4);
        cloumnList.add(AC_MR_LTENCRSRP5);
        cloumnList.add(AC_MR_LTENCRSRQ5);
        cloumnList.add(AC_MR_LTENCPCI5);
        cloumnList.add(AC_MR_LTENCEARFCN5);
        cloumnList.add(AC_MR_LTENCRSRP6);
        cloumnList.add(AC_MR_LTENCRSRQ6);
        cloumnList.add(AC_MR_LTENCPCI6);
        cloumnList.add(AC_MR_LTENCEARFCN6);
        cloumnList.add(AC_MR_LTESCPLRULQCI1);
        cloumnList.add(AC_MR_LTESCPLRULQCI2);
        cloumnList.add(AC_MR_LTESCPLRULQCI3);
        cloumnList.add(AC_MR_LTESCPLRULQCI4);
        cloumnList.add(AC_MR_LTESCPLRULQCI5);
        cloumnList.add(AC_MR_LTESCPLRULQCI6);
        cloumnList.add(AC_MR_LTESCPLRULQCI7);
        cloumnList.add(AC_MR_LTESCPLRULQCI8);
        cloumnList.add(AC_MR_LTESCPLRULQCI9);
        cloumnList.add(AC_MR_LTESCPLRDLQCI1);
        cloumnList.add(AC_MR_LTESCPLRDLQCI2);
        cloumnList.add(AC_MR_LTESCPLRDLQCI3);
        cloumnList.add(AC_MR_LTESCPLRDLQCI4);
        cloumnList.add(AC_MR_LTESCPLRDLQCI5);
        cloumnList.add(AC_MR_LTESCPLRDLQCI6);
        cloumnList.add(AC_MR_LTESCPLRDLQCI7);
        cloumnList.add(AC_MR_LTESCPLRDLQCI8);
        cloumnList.add(AC_MR_LTESCPLRDLQCI9);
        cloumnList.add(AC_MR_LTESCRIP);
        cloumnList.add(AC_MR_LTESCSINRUL);
        cloumnList.add(AC_RRCENDTIME);
        cloumnList.add(AC_LONGITUDE);
        cloumnList.add(AC_LATITUDE);
        cloumnList.add(AC_CELLRBPAYLOAD);
        cloumnList.add(AC_CELLPDCCHPAYLOAD);
        cloumnList.add(AC_CELLPRACHPAYLOAD);
        cloumnList.add(AC_CELLACTUSERNUM);
        cloumnList.add(AC_CELLULRSSI);
        cloumnList.add(ERAB_UE_ULAMBR);
        cloumnList.add(ERAB_UE_DLAMBR);
        cloumnList.add(ERAB_RBID_1);
        cloumnList.add(ERAB_ERABID_1);
        cloumnList.add(ERAB_QCI_1);
        cloumnList.add(ERAB_CREATETIME_1);
        cloumnList.add(ERAB_DEACTIVATETIME_1);
        cloumnList.add(ERAB_RLSRESULT_1);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_1);
        cloumnList.add(ERAB_RLSFAILURECAUSE_1);
        cloumnList.add(ERAB_UL_PKTGWCNT_1);
        cloumnList.add(ERAB_DL_PKTGWCNT_1);
        cloumnList.add(ERAB_UL_BYTEGWCNT_1);
        cloumnList.add(ERAB_DL_BYTEGWCNT_1);
        cloumnList.add(ERAB_UL_PKTUECNT_1);
        cloumnList.add(ERAB_DL_PKTUECNT_1);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE1);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE1);
        cloumnList.add(ERAB_DLMBR_1);
        cloumnList.add(ERAB_ULMBR_1);
        cloumnList.add(ERAB_DLGBR_1);
        cloumnList.add(ERAB_ULGBR_1);
        cloumnList.add(ERAB_RBID_2);
        cloumnList.add(ERAB_ERABID_2);
        cloumnList.add(ERAB_QCI_2);
        cloumnList.add(ERAB_CREATETIME_2);
        cloumnList.add(ERAB_DEACTIVATETIME_2);
        cloumnList.add(ERAB_RLSRESULT_2);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_2);
        cloumnList.add(ERAB_RLSFAILURECAUSE_2);
        cloumnList.add(ERAB_UL_PKTGWCNT_2);
        cloumnList.add(ERAB_DL_PKTGWCNT_2);
        cloumnList.add(ERAB_UL_BYTEGWCNT_2);
        cloumnList.add(ERAB_DL_BYTEGWCNT_2);
        cloumnList.add(ERAB_UL_PKTUECNT_2);
        cloumnList.add(ERAB_DL_PKTUECNT_2);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE2);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE2);
        cloumnList.add(ERAB_DLMBR_2);
        cloumnList.add(ERAB_ULMBR_2);
        cloumnList.add(ERAB_DLGBR_2);
        cloumnList.add(ERAB_ULGBR_2);
        cloumnList.add(ERAB_RBID_3);
        cloumnList.add(ERAB_ERABID_3);
        cloumnList.add(ERAB_QCI_3);
        cloumnList.add(ERAB_CREATETIME_3);
        cloumnList.add(ERAB_DEACTIVATETIME_3);
        cloumnList.add(ERAB_RLSRESULT_3);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_3);
        cloumnList.add(ERAB_RLSFAILURECAUSE_3);
        cloumnList.add(ERAB_UL_PKTGWCNT_3);
        cloumnList.add(ERAB_DL_PKTGWCNT_3);
        cloumnList.add(ERAB_UL_BYTEGWCNT_3);
        cloumnList.add(ERAB_DL_BYTEGWCNT_3);
        cloumnList.add(ERAB_UL_PKTUECNT_3);
        cloumnList.add(ERAB_DL_PKTUECNT_3);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE3);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE3);
        cloumnList.add(ERAB_DLMBR_3);
        cloumnList.add(ERAB_ULMBR_3);
        cloumnList.add(ERAB_DLGBR_3);
        cloumnList.add(ERAB_ULGBR_3);
        cloumnList.add(ERAB_RBID_4);
        cloumnList.add(ERAB_ERABID_4);
        cloumnList.add(ERAB_QCI_4);
        cloumnList.add(ERAB_CREATETIME_4);
        cloumnList.add(ERAB_DEACTIVATETIME_4);
        cloumnList.add(ERAB_RLSRESULT_4);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_4);
        cloumnList.add(ERAB_RLSFAILURECAUSE_4);
        cloumnList.add(ERAB_UL_PKTGWCNT_4);
        cloumnList.add(ERAB_DL_PKTGWCNT_4);
        cloumnList.add(ERAB_UL_BYTEGWCNT_4);
        cloumnList.add(ERAB_DL_BYTEGWCNT_4);
        cloumnList.add(ERAB_UL_PKTUECNT_4);
        cloumnList.add(ERAB_DL_PKTUECNT_4);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE4);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE4);
        cloumnList.add(ERAB_DLMBR_4);
        cloumnList.add(ERAB_ULMBR_4);
        cloumnList.add(ERAB_DLGBR_4);
        cloumnList.add(ERAB_ULGBR_4);
        cloumnList.add(ERAB_RBID_5);
        cloumnList.add(ERAB_ERABID_5);
        cloumnList.add(ERAB_QCI_5);
        cloumnList.add(ERAB_CREATETIME_5);
        cloumnList.add(ERAB_DEACTIVATETIME_5);
        cloumnList.add(ERAB_RLSRESULT_5);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_5);
        cloumnList.add(ERAB_RLSFAILURECAUSE_5);
        cloumnList.add(ERAB_UL_PKTGWCNT_5);
        cloumnList.add(ERAB_DL_PKTGWCNT_5);
        cloumnList.add(ERAB_UL_BYTEGWCNT_5);
        cloumnList.add(ERAB_DL_BYTEGWCNT_5);
        cloumnList.add(ERAB_UL_PKTUECNT_5);
        cloumnList.add(ERAB_DL_PKTUECNT_5);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE5);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE5);
        cloumnList.add(ERAB_DLMBR_5);
        cloumnList.add(ERAB_ULMBR_5);
        cloumnList.add(ERAB_DLGBR_5);
        cloumnList.add(ERAB_ULGBR_5);
        cloumnList.add(ERAB_RBID_6);
        cloumnList.add(ERAB_ERABID_6);
        cloumnList.add(ERAB_QCI_6);
        cloumnList.add(ERAB_CREATETIME_6);
        cloumnList.add(ERAB_DEACTIVATETIME_6);
        cloumnList.add(ERAB_RLSRESULT_6);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_6);
        cloumnList.add(ERAB_RLSFAILURECAUSE_6);
        cloumnList.add(ERAB_UL_PKTGWCNT_6);
        cloumnList.add(ERAB_DL_PKTGWCNT_6);
        cloumnList.add(ERAB_UL_BYTEGWCNT_6);
        cloumnList.add(ERAB_DL_BYTEGWCNT_6);
        cloumnList.add(ERAB_UL_PKTUECNT_6);
        cloumnList.add(ERAB_DL_PKTUECNT_6);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE6);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE6);
        cloumnList.add(ERAB_DLMBR_6);
        cloumnList.add(ERAB_ULMBR_6);
        cloumnList.add(ERAB_DLGBR_6);
        cloumnList.add(ERAB_ULGBR_6);
        cloumnList.add(ERAB_RBID_7);
        cloumnList.add(ERAB_ERABID_7);
        cloumnList.add(ERAB_QCI_7);
        cloumnList.add(ERAB_CREATETIME_7);
        cloumnList.add(ERAB_DEACTIVATETIME_7);
        cloumnList.add(ERAB_RLSRESULT_7);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_7);
        cloumnList.add(ERAB_RLSFAILURECAUSE_7);
        cloumnList.add(ERAB_UL_PKTGWCNT_7);
        cloumnList.add(ERAB_DL_PKTGWCNT_7);
        cloumnList.add(ERAB_UL_BYTEGWCNT_7);
        cloumnList.add(ERAB_DL_BYTEGWCNT_7);
        cloumnList.add(ERAB_UL_PKTUECNT_7);
        cloumnList.add(ERAB_DL_PKTUECNT_7);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE7);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE7);
        cloumnList.add(ERAB_DLMBR_7);
        cloumnList.add(ERAB_ULMBR_7);
        cloumnList.add(ERAB_DLGBR_7);
        cloumnList.add(ERAB_ULGBR_7);
        cloumnList.add(ERAB_RBID_8);
        cloumnList.add(ERAB_ERABID_8);
        cloumnList.add(ERAB_QCI_8);
        cloumnList.add(ERAB_CREATETIME_8);
        cloumnList.add(ERAB_DEACTIVATETIME_8);
        cloumnList.add(ERAB_RLSRESULT_8);
        cloumnList.add(ERAB_SETUPFAILURECAUSE_8);
        cloumnList.add(ERAB_RLSFAILURECAUSE_8);
        cloumnList.add(ERAB_UL_PKTGWCNT_8);
        cloumnList.add(ERAB_DL_PKTGWCNT_8);
        cloumnList.add(ERAB_UL_BYTEGWCNT_8);
        cloumnList.add(ERAB_DL_BYTEGWCNT_8);
        cloumnList.add(ERAB_UL_PKTUECNT_8);
        cloumnList.add(ERAB_DL_PKTUECNT_8);
        cloumnList.add(ERAB_UL_PACKET_DROPRATE8);
        cloumnList.add(ERAB_DL_PACKET_LOSSRATE8);
        cloumnList.add(ERAB_DLMBR_8);
        cloumnList.add(ERAB_ULMBR_8);
        cloumnList.add(ERAB_DLGBR_8);
        cloumnList.add(ERAB_ULGBR_8);
        cloumnList.add(ERAB_DATA_TRANS_UPTIME);
        cloumnList.add(ERAB_DATA_TRANS_DOWNTIME);
        cloumnList.add(ERAB_TOTAL_UPDATA);
        cloumnList.add(ERAB_TOTAL_DOWNDATA);
        cloumnList.add(ERAB_DL_NODATAGWCNTQCI1);
        cloumnList.add(ERAB_UL_NODATAGWCNTQCI1);
        cloumnList.add(ERAB_TYPE);
        cloumnList.add(HO_FIRST_STARTTIME);
        cloumnList.add(HO_FIRST_STARTTIMEMILLISEC);
        cloumnList.add(HO_FIRST_EVENTTYPE);
        cloumnList.add(HO_FIRST_EVENTTIME);
        cloumnList.add(HO_FIRST_TYPE);
        cloumnList.add(HO_FIRST_INTERFACETYPE);
        cloumnList.add(HO_FIRST_SRCMCC);
        cloumnList.add(HO_FIRST_SRCMNC);
        cloumnList.add(HO_FIRST_SRCTAC);
        cloumnList.add(HO_FIRST_SRCCELLID);
        cloumnList.add(HO_FIRST_SRCPCI);
        cloumnList.add(HO_FIRST_TGTMCC);
        cloumnList.add(HO_FIRST_TGTMNC);
        cloumnList.add(HO_FIRST_TGTTAC);
        cloumnList.add(HO_FIRST_TGTCELLID);
        cloumnList.add(HO_FIRST_TGTPCI);
        cloumnList.add(HO_FIRST_RESULT);
        cloumnList.add(HO_FIRST_FAILURECAUSE);
        cloumnList.add(HO_FIRST_ENDTIME);
        cloumnList.add(HO_FIRST_ENDTIMEMILLISEC);
        cloumnList.add(HO_FIRST_SRCULFREQ);
        cloumnList.add(HO_FIRST_SRCDLFREQ);
        cloumnList.add(HO_FIRST_TGTULFREQ);
        cloumnList.add(HO_FIRST_TGTDLFREQ);
        cloumnList.add(HO_FIRST_SRCDLBANDWIDTH);
        cloumnList.add(HO_FIRST_TGTDLBANDWIDTH);
        cloumnList.add(HO_FIRST_SRCRSRP);
        cloumnList.add(HO_FIRST_SRCRSRQ);
        cloumnList.add(HO_FIRST_TGTRSRP);
        cloumnList.add(HO_FIRST_TGTRSRQ);
        cloumnList.add(HO_FIRST_NCNUM);
        cloumnList.add(HO_FIRST_MR_LTENCECGI1);
        cloumnList.add(HO_FIRST_MR_LTENCPCI1);
        cloumnList.add(HO_FIRST_MR_LTENCRSRP1);
        cloumnList.add(HO_FIRST_MR_LTENCRSRQ1);
        cloumnList.add(HO_FIRST_MR_LTENCECGI2);
        cloumnList.add(HO_FIRST_MR_LTENCPCI2);
        cloumnList.add(HO_FIRST_MR_LTENCRSRP2);
        cloumnList.add(HO_FIRST_MR_LTENCRSRQ2);
        cloumnList.add(HO_FIRST_MR_LTENCECGI3);
        cloumnList.add(HO_FIRST_MR_LTENCPCI3);
        cloumnList.add(HO_FIRST_MR_LTENCRSRP3);
        cloumnList.add(HO_FIRST_MR_LTENCRSRQ3);
        cloumnList.add(HO_FIRST_MR_LTENCECGI4);
        cloumnList.add(HO_FIRST_MR_LTENCPCI4);
        cloumnList.add(HO_FIRST_MR_LTENCRSRP4);
        cloumnList.add(HO_FIRST_MR_LTENCRSRQ4);
        cloumnList.add(HO_FIRST_MR_LTENCECGI5);
        cloumnList.add(HO_FIRST_MR_LTENCPCI5);
        cloumnList.add(HO_FIRST_MR_LTENCRSRP5);
        cloumnList.add(HO_FIRST_MR_LTENCRSRQ5);
        cloumnList.add(HO_FIRST_MR_LTENCECGI6);
        cloumnList.add(HO_FIRST_MR_LTENCPCI6);
        cloumnList.add(HO_FIRST_MR_LTENCRSRP6);
        cloumnList.add(HO_FIRST_MR_LTENCRSRQ6);
        cloumnList.add(HO_FIRST_MR_LTESCRIP);
        cloumnList.add(HO_FIRST_MR_LTESCSINRUL);
        cloumnList.add(HO_LAST_STARTTIME);
        cloumnList.add(HO_LAST_STARTTIMEMILLISEC);
        cloumnList.add(HO_LAST_EVENTTYPE);
        cloumnList.add(HO_LAST_EVENTTIME);
        cloumnList.add(HO_LAST_TYPE);
        cloumnList.add(HO_LAST_INTERFACETYPE);
        cloumnList.add(HO_LAST_SRCMCC);
        cloumnList.add(HO_LAST_SRCMNC);
        cloumnList.add(HO_LAST_SRCTAC);
        cloumnList.add(HO_LAST_SRCCELLID);
        cloumnList.add(HO_LAST_SRCPCI);
        cloumnList.add(HO_LAST_TGTMCC);
        cloumnList.add(HO_LAST_TGTMNC);
        cloumnList.add(HO_LAST_TGTTAC);
        cloumnList.add(HO_LAST_TGTCELLID);
        cloumnList.add(HO_LAST_TGTPCI);
        cloumnList.add(HO_LAST_RESULT);
        cloumnList.add(HO_LAST_FAILURECAUSE);
        cloumnList.add(HO_LAST_ENDTIME);
        cloumnList.add(HO_LAST_ENDTIMEMILLISEC);
        cloumnList.add(HO_LAST_SRCULFREQ);
        cloumnList.add(HO_LAST_SRCDLFREQ);
        cloumnList.add(HO_LAST_TGTULFREQ);
        cloumnList.add(HO_LAST_TGTDLFREQ);
        cloumnList.add(HO_LAST_SRCDLBANDWIDTH);
        cloumnList.add(HO_LAST_TGTDLBANDWIDTH);
        cloumnList.add(HO_LAST_SRCRSRP);
        cloumnList.add(HO_LAST_SRCRSRQ);
        cloumnList.add(HO_LAST_TGTRSRP);
        cloumnList.add(HO_LAST_TGTRSRQ);
        cloumnList.add(HO_LAST_NCNUM);
        cloumnList.add(HO_LAST_MR_LTENCECGI1);
        cloumnList.add(HO_LAST_MR_LTENCPCI1);
        cloumnList.add(HO_LAST_MR_LTENCRSRP1);
        cloumnList.add(HO_LAST_MR_LTENCRSRQ1);
        cloumnList.add(HO_LAST_MR_LTENCECGI2);
        cloumnList.add(HO_LAST_MR_LTENCPCI2);
        cloumnList.add(HO_LAST_MR_LTENCRSRP2);
        cloumnList.add(HO_LAST_MR_LTENCRSRQ2);
        cloumnList.add(HO_LAST_MR_LTENCECGI3);
        cloumnList.add(HO_LAST_MR_LTENCPCI3);
        cloumnList.add(HO_LAST_MR_LTENCRSRP3);
        cloumnList.add(HO_LAST_MR_LTENCRSRQ3);
        cloumnList.add(HO_LAST_MR_LTENCECGI4);
        cloumnList.add(HO_LAST_MR_LTENCPCI4);
        cloumnList.add(HO_LAST_MR_LTENCRSRP4);
        cloumnList.add(HO_LAST_MR_LTENCRSRQ4);
        cloumnList.add(HO_LAST_MR_LTENCECGI5);
        cloumnList.add(HO_LAST_MR_LTENCPCI5);
        cloumnList.add(HO_LAST_MR_LTENCRSRP5);
        cloumnList.add(HO_LAST_MR_LTENCRSRQ5);
        cloumnList.add(HO_LAST_MR_LTENCECGI6);
        cloumnList.add(HO_LAST_MR_LTENCPCI6);
        cloumnList.add(HO_LAST_MR_LTENCRSRP6);
        cloumnList.add(HO_LAST_MR_LTENCRSRQ6);
        cloumnList.add(HO_LAST_MR_LTESCRIP);
        cloumnList.add(HO_LAST_MR_LTESCSINRUL);
        cloumnList.add(HO_LAST_CURRENTSGWID);
        cloumnList.add(HO_HISTORYCELLECGI_1);
        cloumnList.add(HO_HISTORYCELLSIZE_1);
        cloumnList.add(HO_HISTORYSTAYTIME_1);
        cloumnList.add(HO_HISTORYCELLECGI_2);
        cloumnList.add(HO_HISTORYCELLSIZE_2);
        cloumnList.add(HO_HISTORYSTAYTIME_2);
        cloumnList.add(HO_HISTORYCELLECGI_3);
        cloumnList.add(HO_HISTORYCELLSIZE_3);
        cloumnList.add(HO_HISTORYSTAYTIME_3);
        cloumnList.add(HO_HISTORYCELLECGI_4);
        cloumnList.add(HO_HISTORYCELLSIZE_4);
        cloumnList.add(HO_HISTORYSTAYTIME_4);
        cloumnList.add(HO_HISTORYCELLECGI_5);
        cloumnList.add(HO_HISTORYCELLSIZE_5);
        cloumnList.add(HO_HISTORYSTAYTIME_5);
        cloumnList.add(HO_HISTORYCELLECGI_6);
        cloumnList.add(HO_HISTORYCELLSIZE_6);
        cloumnList.add(HO_HISTORYSTAYTIME_6);
        cloumnList.add(HO_HISTORYCELLECGI_7);
        cloumnList.add(HO_HISTORYCELLSIZE_7);
        cloumnList.add(HO_HISTORYSTAYTIME_7);
        cloumnList.add(HO_HISTORYCELLECGI_8);
        cloumnList.add(HO_HISTORYCELLSIZE_8);
        cloumnList.add(HO_HISTORYSTAYTIME_8);
        cloumnList.add(RLS_CALLRELEASETIME);
        cloumnList.add(RLS_TAI);
        cloumnList.add(RLS_CELLID);
        cloumnList.add(RLS_PCI);
        cloumnList.add(RLS_MMEIP);
        cloumnList.add(RLS_SGWIP);
        cloumnList.add(RLS_MR_LTESCCQI);
        cloumnList.add(RLS_TM);
        cloumnList.add(RLS_MR_LTESCRI);
        cloumnList.add(RLS_RRCRESULT);
        cloumnList.add(RLS_CALLRELEASECAUSE);
        cloumnList.add(RLS_MR_LTESCRIP);
        cloumnList.add(RLS_MR_LTESCSINRUL);
        cloumnList.add(RLS_MR_LTESCTADV);
        cloumnList.add(RLS_MR_LTESCRSRP);
        cloumnList.add(RLS_MR_LTESCRSRQ);
        cloumnList.add(RLS_MR_LTESCPHR);
        cloumnList.add(RLS_MR_LTESCEARFCN);
        cloumnList.add(RLS_MR_LTENCRSRP1);
        cloumnList.add(RLS_MR_LTENCRSRQ1);
        cloumnList.add(RLS_MR_LTENCPCI1);
        cloumnList.add(RLS_MR_LTENCEARFCN1);
        cloumnList.add(RLS_MR_LTENCRSRP2);
        cloumnList.add(RLS_MR_LTENCRSRQ2);
        cloumnList.add(RLS_MR_LTENCPCI2);
        cloumnList.add(RLS_MR_LTENCEARFCN2);
        cloumnList.add(RLS_MR_LTENCRSRP3);
        cloumnList.add(RLS_MR_LTENCRSRQ3);
        cloumnList.add(RLS_MR_LTENCPCI3);
        cloumnList.add(RLS_MR_LTENCEARFCN3);
        cloumnList.add(RLS_MR_LTENCRSRP4);
        cloumnList.add(RLS_MR_LTENCRSRQ4);
        cloumnList.add(RLS_MR_LTENCPCI4);
        cloumnList.add(RLS_MR_LTENCEARFCN4);
        cloumnList.add(RLS_MR_LTENCRSRP5);
        cloumnList.add(RLS_MR_LTENCRSRQ5);
        cloumnList.add(RLS_MR_LTENCPCI5);
        cloumnList.add(RLS_MR_LTENCEARFCN5);
        cloumnList.add(RLS_MR_LTENCRSRP6);
        cloumnList.add(RLS_MR_LTENCRSRQ6);
        cloumnList.add(RLS_MR_LTENCPCI6);
        cloumnList.add(RLS_MR_LTENCEARFCN6);
        cloumnList.add(RLS_REDIRECTION_TIME);
        cloumnList.add(RLS_REDIRECTION_SYSTEM);
        cloumnList.add(RLS_REDIRECTION_EARFCN);
        cloumnList.add(RLS_LONGITUDE);
        cloumnList.add(RLS_LATITUDE);
        cloumnList.add(RLS_CELLRBPAYLOAD);
        cloumnList.add(RLS_CELLPDCCHPAYLOAD);
        cloumnList.add(RLS_CELLPRACHPAYLOAD);
        cloumnList.add(RLS_CELLACTUSERNUM);
        cloumnList.add(RLS_RESYNCOUNT);
        cloumnList.add(RLS_CALLSTATRELEASE);
        cloumnList.add(UECAP_UECATEGORY);
        cloumnList.add(UECAP_RATTYPE);
        cloumnList.add(UECAP_BANDEUTRA);
        cloumnList.add(UECAP_HALFDUPLEX);
        cloumnList.add(UECAP_ACCESSSTRATUMRELEASE);
        cloumnList.add(UECAP_FGI);
        cloumnList.add(CDMA_TYPE);
        cloumnList.add(CDMA_NCARFCN);
        cloumnList.add(CDMA_PN);
        cloumnList.add(CDMA_CI);
        cloumnList.add(CDMA_PILOTSTRENGTH);
        cloumnList.add(RLF_CONNECTIONFAILURETYPE);
        cloumnList.add(RLF_CELLECGI);
        cloumnList.add(RLF_CELLPCI);
        cloumnList.add(RLF_CELLEARFCN);
        cloumnList.add(RLF_DLRSRP);
        cloumnList.add(RLF_DLRSRQ);
    }
}
